//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationSamplePartialView
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartialView
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string City { get; set; }
        public IEnumerable<PartialView> partialviewDBItems { get; set; }
        //public string JavascriptToRun { get; set; }
    }

    public class LogaraDBList
    {
        public IEnumerable<PartialView> logaraDBItems { get; set; }
    }
}
